### ISSUE TITLE
ITVX Apple TV App Error

### ISSUE THREAD

**Issue by codeonke** [hagezi/dns-blocklists#1984] opened 2023-12-27 09:15 UTC
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi NORMAL

### Which domain(s) should be unblocked?

tom.itv.com

### Why should the domain(s) be unblocked?

Stops all programming from being streamed with an error displayed “Something went wrong our end”. 

Apple TV:

1. Open ITVX
2. Select any program
3. Error displayed

**Comment by hagezi** [comment] 2023-12-27 09:49
Thanks, will be removed.

**Comment by hagezi** [comment] 2023-12-27 10:06
Lee @RainmakerRaw / @mvevitsis: : Can you check this?  https://github.com/hagezi/dns-blocklists/issues/1356

**Comment by RainmakerRaw** [comment] 2023-12-27 10:09
Season's greetings, Gerd / @hagezi! I'll look into this now. I haven't used ITV for a while but the delivery CNAME does indicate they may have started serving ads on the same root as the content. :( Please give me a short while to test, and I'll report back.

**Comment by hagezi** [comment] 2023-12-27 10:12
Many thanks Lee <3

**Comment by mvevitsis** [comment] 2023-12-27 10:20
Blocking that domain on Android still lets me watch the stream - without ads.

**Comment by RainmakerRaw** [comment] 2023-12-27 10:26
Cannot reproduce. 

**DNS server:** AdGuard Home v0.107.43 (latest stable)
**Filter lists:** Hagezi Pro++, Hagezi TIF full

*** Test 1 - Ubuntu 23.10 live USB, Firefox 120 with uBO, WireGuard VPN via VPS in London
ITVX plays movies and TV shows perfectly, including skipping ad breaks without hesitation. No issues detected. 

*** Test 2 - Amazon FireTV stick 4K, native ITVX app, cable ISP connection (northern England)
ITVX plays movies and TV shows perfectly, including skipping ad breaks without hesitation. No issues detected.

*** Test 3 - iPhone 13 Pro Max, native ITVX app, cellular 5G connection
ITVX plays movies and TV shows perfectly, including skipping ad breaks without hesitation. No issues detected. 

Could the OP be in Ireland and impacted due to the implied tying together of the ad server and Irish delivery address? Otherwise, I'm not sure why this would be impacted. I've blocked `tom.itv.com` for years on my personal blacklist without issues, across many devices. @mvevitsis I see no issue on iOS so I doubt tvOS would be much if any different. I'd suspect either an unrelated issue, or perhaps (as above) a geo issue.

**Comment by mvevitsis** [comment] 2023-12-27 10:28
@RainmakerRaw 

It might be specific to the tvOS app. But I too have blocked that domain for years.

**Comment by hagezi** [comment] 2023-12-27 10:28
Thnaks fpr testing @RainmakerRaw @mvevitsis 

@codeonke Can you please check this again as it is not reproducible? Have you deactivated the block page in NextDNS?

**Comment by hagezi** [comment] 2023-12-27 10:32
> I can test it on an actual Apple TV tomorrow.

Thanks!

**Comment by codeonke** [comment] 2023-12-27 10:42
> Thanks for testing @RainmakerRaw @mvevitsis
> 
> @codeonke Can you please check this again as it is not reproducible? Have you deactivated the block page in NextDNS?

I can confirm that I do not have the block page enabled.

I have retested and can confirm it is tvOS specific. With the domain blocked:
Apple TV - “Sorry it looks like there’s an issue with ITVX at our end….”
iPad - Streams work, adverts blocked
iPhone - Streams work, adverts blocked

Location - Bristol, UK

**Comment by hagezi** [comment] 2023-12-27 11:22
@codeonke Thanks, OK, I'll unblock it for light and normal for now.

**Comment by hagezi** [comment] 2023-12-27 12:02
fixed in light and normal.

**Comment by hagezi** [comment] 2024-01-01 13:11
I had more reports about the domain `tom.itv.com` and ITV on Apple TV, they seem to have changed something in the new app version. Furthermore, the unblocking of the domain `ar.prd.content.itv.com` should also be necessary.

By unblocking the domains, no ads are displayed on Apple Tv.

I have now unblocked both domains in all lists as ITV cannot be used on Apple TV.

**Comment by hagezi** [comment] 2024-10-13 11:30
@codeonke @mvevitsis Can you please check again whether the following domains still need to be unblocked for AppleTV:

```
ar.prd.content.itv.com
tom.itv.com
```

Unblocking leads to stream ads being displayed on all other platforms.

**Comment by mvevitsis** [comment] 2024-10-13 11:34
> @codeonke @mvevitsis Can you please check again whether the following domains still need to be unblocked for AppleTV:
> 
> ```
> ar.prd.content.itv.com
> tom.itv.com
> ```
> 
> Unblocking leads to stream ads being displayed on all other platforms.

I will ask my mom to try it, she's the one with the apple TV.

**Comment by hagezi** [comment] 2024-10-13 11:41
Thanks @mvevitsis, Before the test, you have to block the domains

```
ar.prd.content.itv.com
tom.itv.com
```

manually, they are currently no longer included in any list version.

**Comment by codeonke** [comment] 2024-10-13 11:45
I've just tested here with both of the specified domains manually blocked and the Apple TV  ITVX app plays programmes correctly (and without ads).

**Comment by hagezi** [comment] 2024-10-13 11:46
Thanks @codeonke, then I will block the domains again.

**Closed** 2024-10-13 12:33 UTC
Labels: allow
