### ISSUE TITLE
Streameast sports site 

### ISSUE THREAD

**Issue by Poochy1130** [hagezi/dns-blocklists#2694] opened 2024-05-15 23:46 UTC
PopUp ads on https://www.thestreameast.to/v8/

**Comment by Poochy1130** [comment] 2024-05-15 23:48
Hagezi i use streameast to watch the mlb games, starting today ads started getting pass the dns filter and content blocker and I can't access the links but every other site that bloats ads like anime9 and Fmovies all ads there are still being blocked correctly

**Comment by xRuffKez** [comment] 2024-05-16 00:23
Hey @Poochy1130 

To help you out, can you provide a Link to the Page?

**Comment by xRuffKez** [comment] 2024-05-16 00:59
Fixed on next update!

**Comment by Poochy1130** [comment] 2024-05-16 01:02
https://www.thestreameast.to/v8/

**Comment by Poochy1130** [comment] 2024-05-16 01:02
Thank you I found another site to temporary use into this is fixed

**Comment by xRuffKez** [comment] 2024-05-16 01:07
> https://www.thestreameast.to/v8/

Cannot check, geo restricted.

**Comment by hagezi** [comment] 2024-05-16 04:12
For me too, I can't test it.

**Comment by Poochy1130** [comment] 2024-05-16 04:14
Its as if my ad blocker is defenseless on the website that just started happening today it's not my adblock setting cause other sites that host ads are being blocked properly

**Comment by hagezi** [comment] 2024-05-16 04:33
As long as you are not able to find out for yourself what the problem is, we will have to wait for help.

**Comment by hagezi** [comment] 2024-05-16 04:46
@Poochy1130 Which list are you using? I had feedback via Discord that no ads are visible with the Ultimate.

**Comment by hagezi** [comment] 2024-05-16 05:10
There seem to be some new generated popup ads domains on the following IPs:

172.67.178.210
104.21.48.58
172.67.190.154
104.21.65.139

I have added them.

There are no problems with the links, the fact that they are not clickable is not due to the blocklists.

**Closed** 2024-05-16 05:12 UTC
Labels: deny, denylist, geo restricted

**Comment by Poochy1130** [comment] 2024-05-16 06:25
Thank you
