### ISSUE TITLE
Another pack for TikTokz

### ISSUE THREAD

**Issue by nightznero** [hagezi/dns-blocklists#797] opened 2023-03-30 15:21 UTC
Hello HaGeZi,

I see u deleted TikTok list so i cant verify the rules are there bcs any of my text editor cannot handle Pro++ List but here is a few garbage to block(if not blocked yet) from tiktok.
`0.0.0.0 ads-api.tiktok.com`
`0.0.0.0 analytics.tiktok.com`
`0.0.0.0 analytics-sg.tiktok.com`
`0.0.0.0 business-api.tiktok.com`
`0.0.0.0 log.byteoversea.com`
(If they are already blocked sorry for disturbing)
Best regards,
NIGHTZNERO

**Comment by jostrasser** [comment] 2023-04-09 11:53
Hi @hagezi 
since approx. a week (this change?) the Live function of the TikTok Client (iOS) is broken: "bad network connection".

I am right now not able to find out the URL which is breaking it, because I passed my NextDNS installation to verify if it is blocklist related and it looks like that the TikTok Client is caching the specific breaking URL. Maybe a reinstall of the Client helps me to determine it...

I will try to find out the specific URL which we should whitelist / remove it from the blocklist and update you asap. I have to wait until the issue occurs again.

I'll keep you posted.

Thanks and Happy Easter, BR/JO!

**Comment by hagezi** [comment] 2023-04-09 11:57
Thanks, Business API might be a candidate ...

Happy Easter,
Gerd

**Comment by jostrasser** [comment] 2023-04-09 12:02
> Thanks, Business API might be a candidate ...
> 
> Happy Easter,
> Gerd

Exactly my thoughts...
But I will verify it first ;)

Thank you! :)

**Comment by jostrasser** [comment] 2023-04-09 12:39
@hagezi 
Okay, a reinstall did not solve my reproduction issue, but I got a second device with the same behavior:
Impact:
1) Live function broken
2) Profile informations not loaded / blank (Profile Pictures, uploaded videos, ...)
3) Error message in Profile view: No internet connection

There are so many sub-URLs which are playing a role here, I cannot determine it in detail which one is the root cause for it, there are maybe multiple involved.

But the the following URL should be allowed to get it working:
`*.tiktokv.com`

Subs, one of them is breaking it:
```
mon-i18n.tiktokv.com
pitaya-task-i18n.tiktokv.com
rtlog16-normal-useast2a.tiktokv.com
rtlog22-normal-useast2a.tiktokv.com
gecko16-normal-useast2a.tiktokv.com
mssdk19-normal-useast2a.tiktokv.com
log16-normal-useast2a.tiktokv.com
pitaya-i18n.tiktokv.com
frontier-i18n.tiktokv.com
mssdk16-normal-useast2a.tiktokv.com
gecko31-normal-useast2a.tiktokv.com
log22-normal-useast2a.tiktokv.com

```

If these URLs are one time allowed it will work for an unspecified time. I don´t know how often the TT client is testing the connection.

Hope this helps :)

BR/JO!

**Comment by hagezi** [comment] 2023-04-09 13:26
Whitelisted `*mssdk*` for testing ...

**Comment by hagezi** [comment] 2023-04-09 13:32
In the family, TikTok is used extensively on iOS and the problem has never occurred there, it's really hard to find what causes the behavior.

**Comment by jostrasser** [comment] 2023-04-09 13:34
> In the family, TikTok is used extensively on iOS and the problem has never occurred there, it's really hard to find what causes the behavior.

If I can give you more details about it I'll let you know. Monitoring... thanks!

**Comment by hagezi** [comment] 2023-04-11 18:53
@jostrasser Please continue here: https://github.com/hagezi/dns-blocklists/issues/657

Closing ...

**Closed by hagezi** 2023-04-11 18:53 UTC
Labels: white, black
