### ISSUE TITLE
Immomo Network Trackers

### ISSUE THREAD

**Issue by Eow2022yia** [hagezi/dns-blocklists#1099] opened 2023-05-31 16:12 UTC
### Which domain(s) should be blocked?

Hi there, in follow-up to prior request - https://github.com/hagezi/dns-blocklists/issues/819

Can I kindly request client-tracking.tantanapp.com to be blacklisted as well please? This is a tracking domain.

Also despite being marked as fixed it appears that schedule-media.immomo.com, affiliate.tantanapp.com, sla-media.immomo.com are still valid and accessible? Please can this be looked into and blacklisted? Thank you.

### Why should these domain(s) be blocked?

Trackers associated with Chinese dating app Tantan by Hello Group/Immomo.

**Comment by Eow2022yia** [comment] 2023-05-31 18:35
Hi there,

It shows on my logs that the app is making requests to client-tracking.tantanapp.com?

I'm using your Pro+ list on RethinkDNS and all schedule-media.immomo.com, affiliate.tantanapp.com, sla-media.immomo.com are still loading successfully when loading the url(s).

**Comment by hagezi** [comment] 2023-05-31 19:01
Maybe `client-tracking.tantanapp.com` appears in your logs because the app still calls it, but the result of the request is NXDOMAIN. It is dead and therefore no longer on the lists.
The other domains are all blocked.

**Comment by hagezi** [comment] 2023-05-31 19:04
![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/78269793-dd12-4b5b-b010-42a61e931652)

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/976258d3-d958-48aa-9707-d9e4d1b480dc)

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/9a293646-cee6-4b27-a74f-a70d06c2290f)

**Comment by hagezi** [comment] 2023-05-31 19:42
Just tested this, I can confirm that `affiliate.tantanapp.com` is resolved via RethinkDNS with Pro++ although it is on the blocklist.

ping @ignoramous for support.

**Comment by Eow2022yia** [comment] 2023-05-31 19:46
> Just tested this, I can confirm that `affiliate.tantanapp.com` is resolved via RethinkDNS with Pro++ although it is on the blocklist.
> 
> 
> 
> Tested with Apple mobileconfig DoH: https://sky.rethinkdns.com/1:AAoACAgA
> 
> 
> 
> ping @ignoramous for support.

Hi,

Thank you for your help,

Have you tested schedule-media.immomo.com and sla-media.immomo.com as they appear to also be resolving?

Thank you :)

**Comment by hagezi** [comment] 2023-05-31 19:53
Yes, the same behavior with the other domains as well.

**Comment by xRuffKez** [comment] 2023-05-31 20:13
Domain in StevenBlack listed.

**Comment by ignoramous** [comment] 2023-05-31 21:25
Hi,

Thanks for the ping.

First up, apologies that the blocklist updates are lagging. If you will entertain, I've a perfectly valid excuse: Our bills were outstanding with Cloudflare because they seemingly refuse to Indian credit cards like they ought to (recurring charges are illegal, so they can't and shouldn't charge those, but they are attempting to, and are failing). This has meant we couldn't deploy our blocklist updates for over a month.

This past week, I've had one of my (non-Indian) friends pay the bills for us, and kicked started a deploy just now (hopefully, it goes through): https://github.com/serverless-dns/serverless-dns/actions/runs/5137812750

**Comment by ignoramous** [comment] 2023-05-31 21:41
Okay, I just tested against both `sky` and `max` (on [`dohjs.org`](https://dohjs.org/) `https://<max|sky>.rethinkdns.com/1:AAoACAgA`) and I can see that `affiliate.tantanapp.com` is blocked as expected by Multi Pro++

**Comment by hagezi** [comment] 2023-06-01 03:57
Many thanks @ignoramous, all are now blocked as expected.

**Closed by hagezi** 2023-06-01 03:57 UTC
Labels: deny, waiting for feedback, external

**Comment by Eow2022yia** [comment] 2023-06-01 22:02
Thank you very much :) @ignoramous @hagezi @xRuffKez
